project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
pull_request_title: Translations update
pull_request_labels:
  - crowdin
  - i18n
  - translation
commit_message: Updated translations
files:
  - source: /web/i18n/en/translation.json
    translation: /web/i18n/%two_letters_code%/translation.json
