name: Lint

on:
  push:
    paths:
      - '.github/workflows/*'
  pull_request:
    paths:
      - '.github/workflows/*'

jobs:
  actionlint:
    name: GitHub actions
    runs-on: ubuntu-latest
    steps:
      - name: Check out pull request code
        uses: actions/checkout@v4
        if: github.event_name == 'pull_request'
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Check out repository code
        uses: actions/checkout@v4
        if: github.event_name == 'push'

      - uses: docker://rhysd/actionlint:latest
        with:
          args: -shellcheck= -color
