# .github/workflows/chromatic.yml

# Workflow name
name: 'Chromatic'

on:
  push:
    paths:
      - web/**
  pull_request_target:
    paths:
      - web/**

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    if: github.repository == 'owncast/owncast'

    defaults:
      run:
        working-directory: ./web

    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'same_content_newer'

      - name: Check out pull request code
        uses: actions/checkout@v4
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Check out repository code
        uses: actions/checkout@v4
        if: github.event_name == 'push'

      - name: Get changed files
        id: changed-files-yaml
        uses: tj-actions/changed-files@v45
        with:
          path: 'web'
          files_ignore: |
            static/**
            web/next.config.js
          files_yaml: |
            src:
              - '**/*.{js,ts,tsx,jsx,md}'

      - name: Install dependencies
        if: ${{ github.actor != 'renovate[bot]' && github.actor != 'renovate' && steps.changed-files-yaml.outputs.src_any_changed == 'true'}}
        run: npm install

      - name: Publish to Chromatic
        if: ${{ github.actor != 'renovate[bot]' && github.actor != 'renovate' && steps.changed-files-yaml.outputs.src_any_changed == 'true' }}
        uses: chromaui/action@v11

        # Chromatic GitHub Action options
        with:
          workingDir: web
          projectToken: f47410569b62
          onlyChanged: true
