name: javascript-packages
on:
  push:
    paths:
      - openapi.yaml

jobs:
  run:
    name: Generate API Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run redoc on openapi.yaml
        run: |
          npx @redocly/cli --config docs/api/redocly.yaml build-docs openapi.yaml -o docs/api/index.html

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Owncast
          author_email: owncast@owncast.online
          message: 'Commit updated API documentation'
          add: 'docs/api/index.html'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
