name: Lint
on:
  push:
    paths-ignore:
      - 'web/**'
  pull_request:
    paths-ignore:
      - 'web/**'

permissions:
  contents: read

jobs:
  golangci:
    name: Go linter
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'same_content_newer'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.5
          only-new-issues: true
          args: --timeout=3m
